# Generated by Django 5.2.3 on 2025-08-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mykart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cart/'),
        ),
    ]
